Designed FaceDetection Frontend
JuanCorsoMedina/Wil-Project pull request #10
Opened 2024-11-04 20:00 UTC by shivamPrinc

Designed the page for face detection please review and give your feedback.

2024-11-05 22:13 UTC, JuanCorsoMedina requested changes

2024-11-05 22:13 UTC, JuanCorsoMedina commented on front-end/src/components/FaceDetection.js
> +    socket.emit('stop_live_detection');
In the Function "stopDetection", after emitting stop_live_detection, you should update setIsDetecting(false) to ensure it updates correctly after stopping detection.

2024-11-05 22:13 UTC, JuanCorsoMedina commented on front-end/src/components/FaceDetection.js
> +    socket.emit('stop_live_detection');
Check This changes

2024-11-05 22:16 UTC, pavneettoor requested changes

2024-11-05 22:16 UTC, pavneettoor commented on front-end/src/components/FaceDetection.js
> +  useEffect(() => {
There's no error handling for socket connection failures consider adding it.

2024-11-06 22:11 UTC, pavneettoor approved these changes

2024-11-06 22:12 UTC, JuanCorsoMedina approved these changes

2024-11-06 22:12 UTC, merged